services:
  mysql:
    image: mysql:8.0
    container_name: expense_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: expense_manager
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - -h
        - localhost
        - -u
        - appuser
        - -papppassword
      interval: 5s
      timeout: 5s
      retries: 10




  app:
    build: .
    container_name: expense_app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_USER: appuser
      DB_PASSWORD: apppassword
      DB_NAME: expense_manager
    stdin_open: true
    tty: true
    command: python -m app.main




volumes:
  mysql_data:
